package sn.boutique.xamxamboutik.Enums;

public enum TypeRetour {
    REMBOURSEMENT_AVEC_RETOUR_BON_ETAT,
    REMBOURSEMENT_DEFECTUEUX,
    ECHANGE_DEFECTUEUX,
    ECHANGE_CHANGEMENT_PREFERENCE,
    ECHANGE_AJUSTEMENT_PRIX,
    ANNULATION_APRES_LIVRAISON,
    ANNULATION_PARTIELLE,
    ANNULATION_NON_CONFORMITE
}