server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  # Configuration de l'application
  application:
    name: gestion-stock-api

  # Configuration de la base de données
  datasource:
    url: jdbc:postgresql://localhost:5432/xamxamboutk
    username: darousalam
    password: passer
    driver-class-name: org.postgresql.Driver

  # Configuration JPA/Hibernate
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  # Configuration multipart pour les fichiers
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB

# Configuration de la sécurité JWT
security:
  jwt:
    secret-key: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    access-token:
      validity: 3600  # 1 heures en secondes
    refresh-token:
      validity: 70000  # Environ 19.4 heures en secondes

# Configuration des logs
logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
        web: DEBUG
        data: DEBUG
    sn:
      boutique:
        xamxamboutik: DEBUG

# Configuration OpenAPI/Swagger
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    defaultModelsExpandDepth: 1
    defaultModelExpandDepth: 1
    displayRequestDuration: true
    filter: true
  paths-to-match: /**
  packages-to-scan: sn.boutique.backend_darou_salam
  show-actuator: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

# Configuration des CORS (optionnel, à ajuster selon vos besoins)
cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "Authorization"
  allow-credentials: true
  max-age: 3600

# Configuration du serveur (paramètres additionnels)
server.error:
  include-message: always
  include-binding-errors: always
  include-stacktrace: never
  include-exception: false

cloudinary:
  cloud_name: "dee53ktfk"
  api_key: "687276561974881"
  api_secret: "kIlGE9oEoSakLjJqD4dVNk5A6BU"
  # Remplacez par votre API Secret
