server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/v1

spring:
  application:
    name: xamxamboutik-api
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none  # Désactiver pour laisser Flyway gérer les tables
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB

security:
  jwt:
    secret-key:  4e3426cabce49
    access-token:
      validity: 3600
    refresh-token:
      validity: 70000

logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
        web: DEBUG
        data: DEBUG
        boot: DEBUG
        boot.web: DEBUG
      hibernate: DEBUG
      flyway: DEBUG  # Ajouté pour déboguer Flyway
    sn:
      boutique:
        xamxamboutik: DEBUG

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    defaultModelsExpandDepth: 1
    defaultModelExpandDepth: 1
    displayRequestDuration: true
    filter: true
  paths-to-match: /**
  packages-to-scan: sn.boutique.xamxamboutik
  show-actuator: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

server.error:
  include-message: always
  include-binding-errors: always
  include-stacktrace: never
  include-exception: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,https://xamxamboutik.shop}