name: Build and Deploy
on:
  push:
    branches: [ prod ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Spring Boot image
        run: |
          cd backend
          docker buildx build --platform linux/amd64 -t sowbobo98/xamxamboutik-backend:latest --push .
      - name: Build and push React image for darou-salam
        run: |
          cd frontend
          docker buildx build --platform linux/amd64 \
            --build-arg ENV_FILE=.env.darousalam \
            -t sowbobo98/xamxamboutik-frontend-darou:latest --push .
      - name: Build and push React image for hadia
        run: |
          cd frontend
          docker buildx build --platform linux/amd64 \
            --build-arg ENV_FILE=.env.hadia \
            -t sowbobo98/xamxamboutik-frontend-hadia:latest --push .
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/xamxamboutik
            docker login -u sowbobo98 -p ${{ secrets.DOCKER_PASSWORD }}
            docker-compose -f docker-compose-darou.yml -p darou up -d --force-recreate
            docker-compose -f docker-compose-hadia.yml -p hadia up -d --force-recreate
            sudo nginx -t
            sudo systemctl reload nginx