name: Build and Deploy

# Déclenche le pipeline sur un push vers la branche 'prod'
on:
  push:
    branches: [ prod ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Récupère le code source du dépôt
      - name: Checkout code
        uses: actions/checkout@v4

      # Configure Docker Buildx pour la construction multi-plateforme
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Connexion à Docker Hub avec les identifiants sécurisés
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construit et pousse l'image backend
      - name: Build and push Spring Boot image
        run: |
          cd backend
          docker buildx build --platform linux/amd64 -t sowbobo98/xamxamboutik-backend:latest --push .

      # Construit et pousse l'image frontend
      - name: Build and push React image
        run: |
          cd frontend
          docker buildx build --platform linux/amd64 -t sowbobo98/xamxamboutik-frontend:latest --push .

      # Déploie sur le VPS en exécutant les fichiers docker-compose pour chaque client
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/xamxamboutik
            docker login -u sowbobo98 -p ${{ secrets.DOCKER_PASSWORD }}
            # Déploiement pour darou-salam
            docker-compose -f docker-compose-darou-salam.yml pull
            docker-compose -f docker-compose-darou-salam.yml up -d
            # Déploiement pour hadia
            docker-compose -f docker-compose-hadia.yml pull
            docker-compose -f docker-compose-hadia.yml up -d
            # Vérifie et recharge la configuration NGINX
            sudo nginx -t
            sudo systemctl reload nginx