name: Build and Push Docker Images

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Spring Boot image
        run: |
          cd backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/xamxamboutik-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/xamxamboutik-backend:latest

      - name: Build and push React image
        run: |
          cd frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/xamxamboutik-frontend:latest --build-arg ENV_FILE=.env .
          docker push ${{ secrets.DOCKER_USERNAME }}/xamxamboutik-frontend:latest